import localFont from "next/font/local"
import "./globals.css";
import Header from "./layout/header";
import Footer from "./layout/footer";

const square721BTRoman =localFont({
  src: "./font/Square721BTRoman.ttf",
  variable: "--font-square721"
});


export const metadata = {
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${square721BTRoman.variable}`}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
